print("******************************************")
print("*                                        *")
print("*            ANA EKRAN                   *")
print("*                                        *")
print("*  1-HESAP MAKİNASI                      *")
print("*  2-OYUNLAR                             *")
print("*  3-TAKVİM                              *")
print("*  4-TAKVİM                              *")
print("*  5-ÇARPIM TABLOSU                      *")
print("*  6-ÇARPIM TABLOSU                      *")
print("*  7-ÇIKIŞ                               *")
print("*                                        *")
print("*                                        *")
print("******************************************")
secim = input( )
if secim == "1" :print("HESAP MAKİNASI")
if secim == "2" :print("OYUNLAR")
if secim == "3" :print("TAKVİM")
if secim == "4" :print("TAKVİM")
if secim == "5" :print("ÇARPIM TABLOSU")
if secim == "6" :print("ÇARPIM TABLOSU")
if secim == "7" :print("ÇIKIŞ")
if secim in ["1","2","3","4","5","6","7"]: pass
else : print("Yanlış Seçim Yaptınız!")

