print("******************************************")
print("*                                        *")
print("*        HESAP MAKİNASI                  *")
print("*                                        *")
print("*  1-Toplama                             *")
print("*  2-Çıkarma                             *")
print("*  3-Çarpma                              *")
print("*  4-Bölme                               *")
print("*  5-Çıkış                               *")
print("*                                        *")
print("*                                        *")
print("******************************************")
secim = input( )
if secim == "1" :print("Toplama")
if secim == "2" :print("Çıkarma")
if secim == "3" :print("Çarpma")
if secim == "4" :print("Bölme")
if secim == "5" :print("Çıkış")
if secim in ["1","2","3","4","5"]: pass
else : print("Yanlış Seçim Yaptınız!")
