print("******************************************")
print("*                                        *")
print("*            YILAN                       *")
print("*                                        *")
print("*            1-Başla                     *")
print("*                                        *")
print("*                                        *")
print("*                                        *")
print("*                                        *")
print("*             3-Çıkış                    *")
print("******************************************")
secim = input( )
if secim == "1" :print("Yılan")
if secim == "2" :print("Tetris")
if secim == "3" :print("Çıkış")
if secim in ["1","2","3"]: pass
else : print("Yanlış Seçim Yaptınız!")
