
print('******************************************')
print('*                                        *')
print('*                                        *')
print('*                                        *')
print('*                                        *')
print('*     ADI    :SÜLEYMAN                   *')
print('*     SOYADI :GÖKÇE                      *')
print('*                                        *')
print('*                                        *')
print('*                                        *')
print('*                                        *')
print('*                                        *')
print('******************************************')
